name: "krane-eks-action"
description: "Github Action to run Shopify/Krane commands in the Github Workflow."
author: "Deqode"
branding:
  icon: "anchor"
  color: "blue"
inputs:
  command:
    description: "Your command for Krane"
    required: true
outputs:
  result:
    description: "Output returned by your Krane command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
